version: "3"
services:
  redis-server:
    image: redis:latest
    ports:
      - "6377:6379"

  configuration:
    container_name: configuration
    image: configuration:latest
    build: ./configuration/
    volumes:
      - ./configuration/data_dir:/var/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    depends_on:
      - redis-server

  config_manager:
    container_name: config_manager
    image: config_manager:latest
    build: ./config_manager/
    depends_on:
      - configuration

  consul_agent:
    container_name: consul_agent
    image: consul_agent:latest
    build: ./consul_agent/
    depends_on:
      - configuration
      - redis-server

  service_fileupload:
    container_name: service_fileupload
    image: service_fileupload:latest
    build: ./service_fileupload/
    ports:
      - "8082:80"
    depends_on:
      - redis-server