version: "3"
services:
  redis-server:
    image: redis:latest
    ports:
      - "6377:6379"

  configuration:
    container_name: configuration
    image: configuration:latest
    build: ./configuration/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    depends_on:
      - redis-server

  config_manager:
    container_name: config_manager
    image: config_manager:latest
    build: ./config_manager/
    depends_on:
      - configuration

  # consul_daemon:
  #   container_name: consul_daemon
  #   image: consul_daemon:latest
  #   build: ./consul_daemon/
  #   depends_on:
  #     - configuration

  # consul_fileupload:
  #   container_name: consul_fileupload
  #   image: consul_fileupload:latest
  #   build: ./consul_fileupload/
  #   depends_on:
  #     - configuration

  # service_daemon:
  #   container_name: service_daemon
  #   image: service_daemon:latest
  #   build: ./service_daemon/
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - redis-server

  # service_fileupload:
  #   container_name: service_fileupload
  #   image: service_fileupload:latest
  #   build: ./service_fileupload/
  #   ports:
  #     - "8082:8080"
  #   depends_on:
  #     - redis-server