version: "3"
services:
  consul-server:
    container_name: consul-server
    image: consul-server:latest
    build: ./server/
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
  consul-client:
    container_name: consul-client
    image: consul-client:latest
    build: ./client/
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    depends_on:
      - consul-server